Update gridai-run.yml

diff --git a/.github/workflows/gridai-run.yml b/.github/workflows/gridai-run.yml
--- a/.github/workflows/gridai-run.yml
+++ b/.github/workflows/gridai-run.yml
@@ -39,10 +39,14 @@ jobs:
           while [ "$(cat ${JSON_FILE} | jq -c '.[] | .status')" = '"queued"' ]; do echo "waiting on ${RUN_NAME}"; sleep 60; JSON_FILE=$(grid status --export json ${RUN_NAME} | grep Exported | awk '{print $5}'); done
           RUN_STATUS=$(cat ${JSON_FILE} | jq -c '.[] | .status')
           if [[ "${RUN_STATUS}" != '"completed"' ]]; then
-            echo "Error: ${RUN_NAME} exited with {RUN_STATUS}"
+            echo "Error: ${RUN_NAME} completed expected but exited with ${RUN_STATUS}"
             exit 1
           fi
       - run: |
           grid artifacts ${{ env.RUN_NAME }}
+          if [[ $? !- 0 ]]; then
+            echo "Error: ${RUN_NAME} artifacts not found"
+            exit 1
+          fi
           cd ${{ env.RUN_NAME }}*
           ls
