Update gridai-run.yml

diff --git a/.github/workflows/gridai-run.yml b/.github/workflows/gridai-run.yml
--- a/.github/workflows/gridai-run.yml
+++ b/.github/workflows/gridai-run.yml
@@ -34,16 +34,14 @@ jobs:
             echo "Error: grid_name not found in output"
             exit 1
           fi
-
-        - run: |
-          JSON_FILE=$(grid status --export json ${RUN_NAME} | grep Exported | awk '{print $5}')
-          while [ "$(cat ${JSON_FILE} | jq -c '.[] | .status')" = '"queued"' ]; do echo "waiting on ${RUN_NAME}"; sleep 60; JSON_FILE=$(grid status --export json ${RUN_NAME} | grep Exported | awk '{print $5}'); done
-          RUN_STATUS=$(cat ${JSON_FILE} | jq -c '.[] | .status')
-          if [[ "${RUN_STATUS}" != '"completed"' ]]; then
-            echo "Error: ${RUN_NAME} exited with {RUN_STATUS}"
-            exit 1
-          fi
-
+      - run: |
+        JSON_FILE=$(grid status --export json ${RUN_NAME} | grep Exported | awk '{print $5}')
+        while [ "$(cat ${JSON_FILE} | jq -c '.[] | .status')" = '"queued"' ]; do echo "waiting on ${RUN_NAME}"; sleep 60; JSON_FILE=$(grid status --export json ${RUN_NAME} | grep Exported | awk '{print $5}'); done
+        RUN_STATUS=$(cat ${JSON_FILE} | jq -c '.[] | .status')
+        if [[ "${RUN_STATUS}" != '"completed"' ]]; then
+          echo "Error: ${RUN_NAME} exited with {RUN_STATUS}"
+          exit 1
+        fi
       - run: |
           grid artifacts ${{ env.RUN_NAME }}
           cd ${{ env.RUN_NAME }}*
